version: '3.8'
services:
  dpsa-app:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - dpsa-db
    networks:
      - appnet
  dpsa-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - appnet
  dpsa-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
    networks:
      - appnet

volumes:
  dpsadata:

networks:
  appnet:
    driver: bridge
